# yaml-language-server: $schema=../../vendor/doctrine/doctrine-bundle/Resources/config/schema/doctrine-1.0.xsd
doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '18'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
