# yaml-language-server: $schema=../../vendor/nelmio/api-doc-bundle/Resources/config/schema/nelmio_api_doc_bundle.schema.json
nelmio_api_doc:
    documentation:
        info:
            title: Invoicio API
            version: 0.1.0
    areas:
        default:
            path_patterns:
                - ^/app/v1
        app:
            path_patterns:
                - ^/app/v1
        admin:
            path_patterns:
                - ^/admin/v1
        api:
            path_patterns:
                - ^/api/v1
