security:
    password_hashers:
        App\UserBundle\Entity\User: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\UserBundle\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        app:
            pattern: ^/app/v1
            stateless: true
            provider: app_user_provider
            user_checker: App\UserBundle\Security\UserChecker
            json_login:
                check_path: /app/v1/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            jwt: ~

        admin:
            pattern: ^/admin/v1
            stateless: true
            provider: app_user_provider
            user_checker: App\UserBundle\Security\UserChecker
            json_login:
                check_path: /admin/v1/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            jwt: ~

        api:
            pattern: ^/api/v1
            stateless: true
            custom_authenticators:
                - App\ApiBundle\Security\ApiTokenAuthenticator

    access_control:
        - { path: ^/app/v1/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin/v1/login, roles: PUBLIC_ACCESS }
        - { path: ^/app/v1/health, roles: PUBLIC_ACCESS }
        - { path: ^/admin/v1/health, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1/health, roles: PUBLIC_ACCESS }
        - { path: ^/app/v1/doc, roles: PUBLIC_ACCESS }
        - { path: ^/admin/v1/doc, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1/doc, roles: PUBLIC_ACCESS }
        - { path: ^/admin/v1, roles: ROLE_ADMIN }
        - { path: ^/app/v1, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/v1, roles: ROLE_API }
