nelmio_api_doc:
    resource: '@NelmioApiDocBundle/config/routing/swaggerui.xml'
    prefix: /api/doc

nelmio_api_doc_json:
    path: /api/doc.json
    methods: [GET]
    defaults:
        _controller: nelmio_api_doc.controller.swagger_json
